# Generated by Django 4.1.8 on 2023-05-27 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("halls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hallfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hall",
            name="event_type",
            field=models.ManyToManyField(
                blank=True, related_name="halls", to="halls.eventtype"
            ),
        ),
        migrations.AddField(
            model_name="hall",
            name="hall_type",
            field=models.ManyToManyField(
                blank=True, related_name="halls", to="halls.halltype"
            ),
        ),
        migrations.AddField(
            model_name="hall",
            name="moderated",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="halls.hallmoderatingstatus",
            ),
        ),
        migrations.AddField(
            model_name="hall",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="halls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hall",
            name="unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="halls.unit"
            ),
        ),
    ]
