# Generated by Django 4.1.8 on 2023-05-27 11:17

from django.db import migrations, models
import django.db.models.deletion
import halls.models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0005_alter_hall_moderated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="address",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hall",
            name="area_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hall",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="capacity_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="condition",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=halls.models.hall_directory_path_to_condition,
            ),
        ),
        migrations.AlterField(
            model_name="hall",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hall",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hall",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="services",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="site",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="telegram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="halls.unit",
            ),
        ),
        migrations.AlterField(
            model_name="hall",
            name="view_count",
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="hall",
            name="vk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
